### PR TITLE
Update preprocess_ifc.py

### PR DESCRIPTION
**Pull request by jmcouffin**
I had to edit like so to make it work on my computer (a windows machine)

### CODE REVIEW

**Comment by jmcouffin** [comment]
```
C:\pyRevit\_WWW_playground\3DVerse\demo-ifc-next\public\scripts>python preprocess_ifc.py
Traceback (most recent call last):
  File "C:\pyRevit\_WWW_playground\3DVerse\demo-ifc-next\public\scripts\preprocess_ifc.py", line 60, in <module>
    e_json["psets"] = ifcopenshell.util.element.get_psets(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'ifcopenshell.util' has no attribute 'element'
```

**Comment by johltn** [comment]
which python and which ifcopenshell versions are you using?

**Comment by jmcouffin** [comment]
> which python and which ifcopenshell versions are you using?

- 3.12.6 for python
- ifcopenshell 0.8.0

**Comment by johltn** [comment]
Thanks!

**Pull request merged**
